spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dev_db
    username: root
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
       dialect: org.hibernate.dialect.MySQL5Dialect
healthcare:
  management:
   vitalsign:
     uri: http://localhost:8090/vitalSign
     name: Healthcare-Management-VitalSign-API 
   user:
     uri: http://localhost:8080/users
     name: Healthcare-Management-User-API 
   patient:
    uri: http://localhost:8089/patient
    name: Healthcare-Management-Patient-API
