spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/user_db
    username: ${username}
    password: ${password}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
       dialect: org.hibernate.dialect.MySQL5Dialect
  cache:
    type: redis
    redis:
      cache-null-values: true
      time-to-live: 600000
  redis:
    host: host.docker.internal
    port: 6379
    
healthcare:
  management:
   vitalsign:
     uri: http://host.docker.internal:8090/vitalSign
     name: Healthcare-Management-VitalSign-API 
   user:
     uri: http://host.docker.internal:8080/users
     name: Healthcare-Management-User-API 
   patient:
    uri: http://host.docker.internal:8089/patient
    name: Healthcare-Management-Patient-API
